language: php

php:
  - 7.1

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - mysql -e 'CREATE DATABASE homestead;'
  - cp .env.travis .env.testing
  - chmod -R 777 app/storage
  - php artisan migrate:install --env=testing --no-interaction -vvv

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/codecept run functional
  - php artisan migrate:rollback --env=testing --no-interaction -vvv
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --dry-run --diff
  - vendor/bin/phpunit

notifications:
  email: false
